In [1]:
import numpy as np
import datetime

#import pandas pd
import pandas as pd 

In [2]:
#functions from my ICON project
def rotate_array(working_array, rotate_value):
    '''
    rotates the ICON 90, 180 or 270 degrees
    returns rotated ICON
    
    '''
    #print(working_array)
    if rotate_value == 1:
        rotate_array = np.rot90(working_array)
    elif rotate_value == 2:
        rotate_array = np.rot90(working_array,2) 
    else:
        rotate_array = np.rot90(working_array,3)
    #print(rotate_array)    
    return rotate_array

def print_icon(on_print_char, off_print_char,print_array):
    '''
    prints the icon to the screen   
    '''
    
    array_shape = np.shape(print_array)
    #print('array_shape',array_shape)
    shape_row = array_shape[0]
    shape_col = array_shape[1]
    # build string array using off_print_char as the initial value
    output_array = np.full((shape_row,shape_col),off_print_char,dtype=str)
    #print(output_array)
    #print blank line
    print('')
    
    for row in range(shape_row):
        print_line=''
        for col in range(shape_col):
            #print('r/c', row, col)
            if print_array[row,col] == 1:
                output_array[row,col] = on_print_char 
            print_line=print_line+(str(output_array[row,col]))
        print(print_line)

In [3]:
#build empty 3X4 array
test_array = np.full((3, 4),0,dtype=int)
print(test_array)
test_array = np.array([(1,0,1,0) , (0,1,0,1), (1,1,1,1)])
print(np.shape(test_array)) 
print(test_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
[[1 0 1 0]
 [0 1 0 1]
 [1 1 1 1]]


In [4]:
on_value = '#'
off_value = ' '

print_icon(on_value, off_value,test_array)


# # 
 # #
####


In [5]:
#change to dataframe

test_array_df = pd.DataFrame(test_array)

#print
test_array_df

0  1  2  3
0  1  0  1  0
1  0  1  0  1
2  1  1  1  1

In [6]:
#print with no headers or index
print(test_array_df.to_string(index=False,header=False))


 1  0  1  0
 0  1  0  1
 1  1  1  1


In [7]:
# change my array to pandas dataframe
# maybe better way to print since pandas has lots of options
test_array2_df = pd.DataFrame(rotate_array(test_array,1))


In [8]:
test_array2_df

0  1  2
0  0  1  1
1  1  0  1
2  0  1  1
3  1  0  1

In [9]:
print(test_array2_df.to_string(index=False,header=False))

 0  1  1
 1  0  1
 0  1  1
 1  0  1
